# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import server_pb2 as server__pb2


class WebSiteServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserFollowUpdate = channel.unary_stream(
                '/webSiteGRPC.WebSiteService/GetUserFollowUpdate',
                request_serializer=server__pb2.userInfo.SerializeToString,
                response_deserializer=server__pb2.videoInfoResponse.FromString,
                )
        self.GetUserViewHistory = channel.unary_stream(
                '/webSiteGRPC.WebSiteService/GetUserViewHistory',
                request_serializer=server__pb2.userInfo.SerializeToString,
                response_deserializer=server__pb2.videoInfoResponse.FromString,
                )
        self.GetVideoList = channel.unary_stream(
                '/webSiteGRPC.WebSiteService/GetVideoList',
                request_serializer=server__pb2.getVideoListRequest.SerializeToString,
                response_deserializer=server__pb2.videoInfoResponse.FromString,
                )
        self.GetHotVideoList = channel.unary_stream(
                '/webSiteGRPC.WebSiteService/GetHotVideoList',
                request_serializer=server__pb2.getVideoListRequest.SerializeToString,
                response_deserializer=server__pb2.videoInfoResponse.FromString,
                )
        self.GetSelfInfo = channel.unary_unary(
                '/webSiteGRPC.WebSiteService/GetSelfInfo',
                request_serializer=server__pb2.userInfo.SerializeToString,
                response_deserializer=server__pb2.AuthorInfoResponse.FromString,
                )


class WebSiteServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserFollowUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserViewHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVideoList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHotVideoList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSelfInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WebSiteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserFollowUpdate': grpc.unary_stream_rpc_method_handler(
                    servicer.GetUserFollowUpdate,
                    request_deserializer=server__pb2.userInfo.FromString,
                    response_serializer=server__pb2.videoInfoResponse.SerializeToString,
            ),
            'GetUserViewHistory': grpc.unary_stream_rpc_method_handler(
                    servicer.GetUserViewHistory,
                    request_deserializer=server__pb2.userInfo.FromString,
                    response_serializer=server__pb2.videoInfoResponse.SerializeToString,
            ),
            'GetVideoList': grpc.unary_stream_rpc_method_handler(
                    servicer.GetVideoList,
                    request_deserializer=server__pb2.getVideoListRequest.FromString,
                    response_serializer=server__pb2.videoInfoResponse.SerializeToString,
            ),
            'GetHotVideoList': grpc.unary_stream_rpc_method_handler(
                    servicer.GetHotVideoList,
                    request_deserializer=server__pb2.getVideoListRequest.FromString,
                    response_serializer=server__pb2.videoInfoResponse.SerializeToString,
            ),
            'GetSelfInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSelfInfo,
                    request_deserializer=server__pb2.userInfo.FromString,
                    response_serializer=server__pb2.AuthorInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'webSiteGRPC.WebSiteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WebSiteService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserFollowUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/webSiteGRPC.WebSiteService/GetUserFollowUpdate',
            server__pb2.userInfo.SerializeToString,
            server__pb2.videoInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserViewHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/webSiteGRPC.WebSiteService/GetUserViewHistory',
            server__pb2.userInfo.SerializeToString,
            server__pb2.videoInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVideoList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/webSiteGRPC.WebSiteService/GetVideoList',
            server__pb2.getVideoListRequest.SerializeToString,
            server__pb2.videoInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHotVideoList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/webSiteGRPC.WebSiteService/GetHotVideoList',
            server__pb2.getVideoListRequest.SerializeToString,
            server__pb2.videoInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSelfInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/webSiteGRPC.WebSiteService/GetSelfInfo',
            server__pb2.userInfo.SerializeToString,
            server__pb2.AuthorInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
