# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import server_pb2 as server__pb2


class WebSiteServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserFollowUpdate = channel.unary_stream(
                '/webSiteGRPC.WebSiteService/GetUserFollowUpdate',
                request_serializer=server__pb2.userInfo.SerializeToString,
                response_deserializer=server__pb2.videoInfoResponse.FromString,
                )
        self.GetUserViewHistory = channel.unary_stream(
                '/webSiteGRPC.WebSiteService/GetUserViewHistory',
                request_serializer=server__pb2.userInfo.SerializeToString,
                response_deserializer=server__pb2.videoInfoResponse.FromString,
                )
        self.GetUserFollowList = channel.unary_stream(
                '/webSiteGRPC.WebSiteService/GetUserFollowList',
                request_serializer=server__pb2.userInfo.SerializeToString,
                response_deserializer=server__pb2.AuthorInfoResponse.FromString,
                )
        self.GetUserCollectionList = channel.unary_stream(
                '/webSiteGRPC.WebSiteService/GetUserCollectionList',
                request_serializer=server__pb2.collectionInfoRequest.SerializeToString,
                response_deserializer=server__pb2.collectionInfo.FromString,
                )
        self.GetHotVideoList = channel.unary_stream(
                '/webSiteGRPC.WebSiteService/GetHotVideoList',
                request_serializer=server__pb2.getVideoListRequest.SerializeToString,
                response_deserializer=server__pb2.videoInfoResponse.FromString,
                )
        self.GetSelfInfo = channel.unary_unary(
                '/webSiteGRPC.WebSiteService/GetSelfInfo',
                request_serializer=server__pb2.userInfo.SerializeToString,
                response_deserializer=server__pb2.AuthorInfoResponse.FromString,
                )
        self.GetWaitWatchList = channel.unary_unary(
                '/webSiteGRPC.WebSiteService/GetWaitWatchList',
                request_serializer=server__pb2.userInfo.SerializeToString,
                response_deserializer=server__pb2.collectionInfo.FromString,
                )
        self.GetVideoDetail = channel.stream_stream(
                '/webSiteGRPC.WebSiteService/GetVideoDetail',
                request_serializer=server__pb2.getVideoListRequest.SerializeToString,
                response_deserializer=server__pb2.VideoDetailResponse.FromString,
                )


class WebSiteServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserFollowUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserViewHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserFollowList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserCollectionList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHotVideoList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSelfInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWaitWatchList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVideoDetail(self, request_iterator, context):
        """获取基础信息。以下接口全部使用代理发送请求
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WebSiteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserFollowUpdate': grpc.unary_stream_rpc_method_handler(
                    servicer.GetUserFollowUpdate,
                    request_deserializer=server__pb2.userInfo.FromString,
                    response_serializer=server__pb2.videoInfoResponse.SerializeToString,
            ),
            'GetUserViewHistory': grpc.unary_stream_rpc_method_handler(
                    servicer.GetUserViewHistory,
                    request_deserializer=server__pb2.userInfo.FromString,
                    response_serializer=server__pb2.videoInfoResponse.SerializeToString,
            ),
            'GetUserFollowList': grpc.unary_stream_rpc_method_handler(
                    servicer.GetUserFollowList,
                    request_deserializer=server__pb2.userInfo.FromString,
                    response_serializer=server__pb2.AuthorInfoResponse.SerializeToString,
            ),
            'GetUserCollectionList': grpc.unary_stream_rpc_method_handler(
                    servicer.GetUserCollectionList,
                    request_deserializer=server__pb2.collectionInfoRequest.FromString,
                    response_serializer=server__pb2.collectionInfo.SerializeToString,
            ),
            'GetHotVideoList': grpc.unary_stream_rpc_method_handler(
                    servicer.GetHotVideoList,
                    request_deserializer=server__pb2.getVideoListRequest.FromString,
                    response_serializer=server__pb2.videoInfoResponse.SerializeToString,
            ),
            'GetSelfInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSelfInfo,
                    request_deserializer=server__pb2.userInfo.FromString,
                    response_serializer=server__pb2.AuthorInfoResponse.SerializeToString,
            ),
            'GetWaitWatchList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWaitWatchList,
                    request_deserializer=server__pb2.userInfo.FromString,
                    response_serializer=server__pb2.collectionInfo.SerializeToString,
            ),
            'GetVideoDetail': grpc.stream_stream_rpc_method_handler(
                    servicer.GetVideoDetail,
                    request_deserializer=server__pb2.getVideoListRequest.FromString,
                    response_serializer=server__pb2.VideoDetailResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'webSiteGRPC.WebSiteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WebSiteService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserFollowUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/webSiteGRPC.WebSiteService/GetUserFollowUpdate',
            server__pb2.userInfo.SerializeToString,
            server__pb2.videoInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserViewHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/webSiteGRPC.WebSiteService/GetUserViewHistory',
            server__pb2.userInfo.SerializeToString,
            server__pb2.videoInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserFollowList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/webSiteGRPC.WebSiteService/GetUserFollowList',
            server__pb2.userInfo.SerializeToString,
            server__pb2.AuthorInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserCollectionList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/webSiteGRPC.WebSiteService/GetUserCollectionList',
            server__pb2.collectionInfoRequest.SerializeToString,
            server__pb2.collectionInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHotVideoList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/webSiteGRPC.WebSiteService/GetHotVideoList',
            server__pb2.getVideoListRequest.SerializeToString,
            server__pb2.videoInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSelfInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/webSiteGRPC.WebSiteService/GetSelfInfo',
            server__pb2.userInfo.SerializeToString,
            server__pb2.AuthorInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWaitWatchList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/webSiteGRPC.WebSiteService/GetWaitWatchList',
            server__pb2.userInfo.SerializeToString,
            server__pb2.collectionInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVideoDetail(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/webSiteGRPC.WebSiteService/GetVideoDetail',
            server__pb2.getVideoListRequest.SerializeToString,
            server__pb2.VideoDetailResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
